# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Rminstd_rand <- function(length) {
    .Call(`_testRcpp_Rminstd_rand`, length)
}

Rmt19937 <- function(length) {
    .Call(`_testRcpp_Rmt19937`, length)
}

Rknuth_b <- function(length) {
    .Call(`_testRcpp_Rknuth_b`, length)
}

Rminstd_rand.int <- function(length) {
    .Call(`_testRcpp_Rminstd_rand_int`, length)
}

Rmt19937.int <- function(length) {
    .Call(`_testRcpp_Rmt19937_int`, length)
}

Rknuth_b.int <- function(length) {
    .Call(`_testRcpp_Rknuth_b_int`, length)
}

Sample <- function(input, size, replace = FALSE) {
    .Call(`_testRcpp_Sample`, input, size, replace)
}

Sample.int <- function(input, size, replace = FALSE) {
    .Call(`_testRcpp_sample_int`, input, size, replace)
}

startsWith <- function(str, substr) {
    .Call(`_testRcpp_startsWith`, str, substr)
}

endsWith <- function(str, substr) {
    .Call(`_testRcpp_endsWith`, str, substr)
}

replaceSubstring <- function(s, oldSubstr, newSubstr) {
    .Call(`_testRcpp_replaceSubstring`, s, oldSubstr, newSubstr)
}

toTable.char <- function(x) {
    .Call(`_testRcpp_toTable_char`, x)
}

power_vector <- function(x, power) {
    .Call(`_testRcpp_power_vector`, x, power)
}

toTable <- function(x) {
    .Call(`_testRcpp_toTable`, x)
}

