# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

power_vector <- function(x, power) {
    .Call(`_testRcpp_power_vector`, x, power)
}

sqrt_vector <- function(x) {
    .Call(`_testRcpp_sqrt_vector`, x)
}

sum_vector <- function(x) {
    .Call(`_testRcpp_sum_vector`, x)
}

divide_vector <- function(x, divisor) {
    .Call(`_testRcpp_divide_vector`, x, divisor)
}

multiply_vector <- function(x, multiplier) {
    .Call(`_testRcpp_multiply_vector`, x, multiplier)
}

toTable <- function(x) {
    .Call(`_testRcpp_toTable`, x)
}

create_rng_int <- function() {
    .Call(`_testRcpp_create_rng_int`)
}

generate_minstd_rand0_sequence <- function(length) {
    .Call(`_testRcpp_generate_minstd_rand0_sequence`, length)
}

generate_minstd_rand_sequence <- function(length) {
    .Call(`_testRcpp_generate_minstd_rand_sequence`, length)
}

generate_mt19937_sequence <- function(length) {
    .Call(`_testRcpp_generate_mt19937_sequence`, length)
}

generate_mt19937_64_sequence <- function(length) {
    .Call(`_testRcpp_generate_mt19937_64_sequence`, length)
}

generate_ranlux24_base_sequence <- function(length) {
    .Call(`_testRcpp_generate_ranlux24_base_sequence`, length)
}

generate_ranlux48_base_sequence <- function(length) {
    .Call(`_testRcpp_generate_ranlux48_base_sequence`, length)
}

generate_ranlux24_sequence <- function(length) {
    .Call(`_testRcpp_generate_ranlux24_sequence`, length)
}

generate_ranlux48_sequence <- function(length) {
    .Call(`_testRcpp_generate_ranlux48_sequence`, length)
}

generate_knuth_b_sequence <- function(length) {
    .Call(`_testRcpp_generate_knuth_b_sequence`, length)
}

generate_default_random_engine_sequence <- function(length) {
    .Call(`_testRcpp_generate_default_random_engine_sequence`, length)
}

generate_subtract_with_carry_engine_sequence <- function(length) {
    .Call(`_testRcpp_generate_subtract_with_carry_engine_sequence`, length)
}

generate_subtract_with_carry_engine_64_sequence <- function(length) {
    .Call(`_testRcpp_generate_subtract_with_carry_engine_64_sequence`, length)
}

sample <- function(input, size, replace = FALSE) {
    .Call(`_testRcpp_sample`, input, size, replace)
}

sample_int <- function(input, size, replace = FALSE) {
    .Call(`_testRcpp_sample_int`, input, size, replace)
}

containsSubstring <- function(str, substr) {
    .Call(`_testRcpp_containsSubstring`, str, substr)
}

toUpperCase <- function(s) {
    .Call(`_testRcpp_toUpperCase`, s)
}

trim <- function(s) {
    .Call(`_testRcpp_trim`, s)
}

startsWith <- function(str, substr) {
    .Call(`_testRcpp_startsWith`, str, substr)
}

endsWith <- function(str, substr) {
    .Call(`_testRcpp_endsWith`, str, substr)
}

replaceSubstring <- function(s, oldSubstr, newSubstr) {
    .Call(`_testRcpp_replaceSubstring`, s, oldSubstr, newSubstr)
}

toTable_char <- function(x) {
    .Call(`_testRcpp_toTable_char`, x)
}

